language: node_js

sudo: false

node_js:
  - "7"

cache:
  apt: true
  directories:
    - node_modules

addons:
  ssh_known_hosts: github.com

script:
  - 'npm run build'
  - 'npm run clean'
  - 'npm run deploy  "${TRAVIS_PULL_REQUEST}"'

branches:
  only:
    - v2

env:
  global:
    - GH_REPO: "github.com/o2team/o2team.github.io.git"
    - secure: "TU5kkhDIMdFkWZZ4VRK3Vj+K6bFbE+AosjMi0cXJSsrZsD2bHAkAps2Wi9+/NHfTt+cuEKFaYXE4EYrSWmNoC1dXTasQEuo1OBOL5WZjPzNX1u7takERPMCCExrKWlOt18Ywxpqg4OUtYUlHH3g7FtB5HRB2ne0bN4BwdrHLpHP3i0U83R4IdOe6xbjDKMT0DRv5FizWfCUXEcIlQ6z2Ywd1UDXd9JVbLl5VR6f8c5UabV1/5hn19dguNuK7ctlUuWcLVZpABDSL2JlMZyoBRycRpPGeIMt5TBMncvk8vYhnZdx7gaSAEPvYy+RmGeEQbDgxejzaxgB5sB7m8tDjddVcnqlOKKoH/s3t3ETWvsahJcRtxXFHj+bAGcfr7r1Ul0hWDCWrtUgLeokNQoX9R3fhwTAJoFMpMZyopzoUih5QfO/jAMNugbzjrAd9AmBUujgDXNqFcOiLnvOGl8UnpFVnphMTIcqU3i2QZhH45rq0kfB8piZ1daCRt6gvGIerwbdtyuXswoOAPyiiYptpX6rlxV7gB420E0PY8NeZzmqISNAdd4n2DESMgOHmmPV8gELjjJrbWAQ/icoK1DATgdo9rfD3Ex/peLxVPb+VBBMiYaPHT6Ib4Pi4V3qRaQPbmsICmGXUgGkkXpIMPeu0m8E4UGrlyLry2JrnzwYqYDc="
